export const TEAM_CODES = {
  // Seoul Region Teams (Region: 1)
  '1211': { team: 'YSEagles', region: 'Seoul', role: 'coach' },
  '1672': { team: 'YSEagles', region: 'Seoul', role: 'player' },
  '1231': { team: 'SNGreenTerrors', region: 'Seoul', role: 'coach' },
  '1232': { team: 'SNGreenTerrors', region: 'Seoul', role: 'player' },
  '1971': { team: 'HYLions', region: 'Seoul', role: 'coach' },
  '1142': { team: 'HYLions', region: 'Seoul', role: 'player' },
  '1741': { team: 'KMRazorbacks', region: 'Seoul', role: 'coach' },
  '1092': { team: 'KMRazorbacks', region: 'Seoul', role: 'player' },
  '1081': { team: 'USCityhawks', region: 'Seoul', role: 'coach' },
  '1982': { team: 'USCityhawks', region: 'Seoul', role: 'player' },
  '1511': { team: 'HFBlackKnights', region: 'Seoul', role: 'coach' },
  '1762': { team: 'HFBlackKnights', region: 'Seoul', role: 'player' },
  '1871': { team: 'KKRagingBulls', region: 'Seoul', role: 'coach' },
  '1802': { team: 'KKRagingBulls', region: 'Seoul', role: 'player' },
  '1371': { team: 'HICowboys', region: 'Seoul', role: 'coach' },
  '1922': { team: 'HICowboys', region: 'Seoul', role: 'player' },
  '1271': { team: 'KUTigers', region: 'Seoul', role: 'coach' },
  '1785': { team: 'KUTigers', region: 'Seoul', role: 'player' },
  '1991': { team: 'DGTuskers', region: 'Seoul', role: 'coach' },
  '1131': { team: 'DGTuskers', region: 'Seoul', role: 'player' },
  '1611': { team: 'SSCrusaders', region: 'Seoul', role: 'coach' },
  '1782': { team: 'SSCrusaders', region: 'Seoul', role: 'player' },
  '1951': { team: 'CABlueDragons', region: 'Seoul', role: 'coach' },
  '1112': { team: 'CABlueDragons', region: 'Seoul', role: 'player' },
  '1071': { team: 'KHCommanders', region: 'Seoul', role: 'coach' },
  '1752': { team: 'KHCommanders', region: 'Seoul', role: 'player' },
  '1421': { team: 'SGAlbatross', region: 'Seoul', role: 'coach' },
  '1492': { team: 'SGAlbatross', region: 'Seoul', role: 'player' },

  // Gyeonggi-Gangwon Region Teams (Region: 2)
  '2751': { team: 'SKRoyals', region: 'Gyeonggi-Gangwon', role: 'coach' },
  '2912': { team: 'SKRoyals', region: 'Gyeonggi-Gangwon', role: 'player' },
  '2011': { team: 'KWCapras', region: 'Gyeonggi-Gangwon', role: 'coach' },
  '2182': { team: 'KWCapras', region: 'Gyeonggi-Gangwon', role: 'player' },
  '2119': { team: 'DKKodiakBears', region: 'Gyeonggi-Gangwon', role: 'coach' },
  '2662': { team: 'DKKodiakBears', region: 'Gyeonggi-Gangwon', role: 'player' },
  '2081': { team: 'YIWhiteTigers', region: 'Gyeonggi-Gangwon', role: 'coach' },
  '2742': { team: 'YIWhiteTigers', region: 'Gyeonggi-Gangwon', role: 'player' },
  '2871': { team: 'IHTealDragons', region: 'Gyeonggi-Gangwon', role: 'coach' },
  '2902': { team: 'IHTealDragons', region: 'Gyeonggi-Gangwon', role: 'player' },
  '2111': { team: 'HLPhoenix', region: 'Gyeonggi-Gangwon', role: 'coach' },
  '2762': { team: 'HLPhoenix', region: 'Gyeonggi-Gangwon', role: 'player' },
  '2521': { team: 'HSKillerWhales', region: 'Gyeonggi-Gangwon', role: 'coach' },
  '2952': {
    team: 'HSKillerWhales',
    region: 'Gyeonggi-Gangwon',
    role: 'player',
  },

  // Daegu-Gyeongbuk Region Teams (Region: 3)
  '3761': {
    team: 'KBOrangeFighters',
    region: 'Daegu-Gyeongbuk',
    role: 'coach',
  },
  '3092': {
    team: 'KBOrangeFighters',
    region: 'Daegu-Gyeongbuk',
    role: 'player',
  },
  '3011': { team: 'KIBlackBears', region: 'Daegu-Gyeongbuk', role: 'coach' },
  '3882': { team: 'KIBlackBears', region: 'Daegu-Gyeongbuk', role: 'player' },
  '3911': { team: 'KMSuperLions', region: 'Daegu-Gyeongbuk', role: 'coach' },
  '3212': { team: 'KMSuperLions', region: 'Daegu-Gyeongbuk', role: 'player' },
  '3331': { team: 'KOTRavens', region: 'Daegu-Gyeongbuk', role: 'coach' },
  '3342': { team: 'KOTRavens', region: 'Daegu-Gyeongbuk', role: 'player' },
  '3381': { team: 'DCUScudAngels', region: 'Daegu-Gyeongbuk', role: 'coach' },
  '3352': { team: 'DCUScudAngels', region: 'Daegu-Gyeongbuk', role: 'player' },
  '3981': { team: 'DUFlyingTigers', region: 'Daegu-Gyeongbuk', role: 'coach' },
  '3042': { team: 'DUFlyingTigers', region: 'Daegu-Gyeongbuk', role: 'player' },
  '3271': { team: 'DHURhinos', region: 'Daegu-Gyeongbuk', role: 'coach' },
  '3822': { team: 'DHURhinos', region: 'Daegu-Gyeongbuk', role: 'player' },
  '3671': {
    team: 'DGWhiteElephants',
    region: 'Daegu-Gyeongbuk',
    role: 'coach',
  },
  '3592': {
    team: 'DGWhiteElephants',
    region: 'Daegu-Gyeongbuk',
    role: 'player',
  },
  '3991': { team: 'YNPegasus', region: 'Daegu-Gyeongbuk', role: 'coach' },
  '3612': { team: 'YNPegasus', region: 'Daegu-Gyeongbuk', role: 'player' },
  '3871': { team: 'HDHolyRams', region: 'Daegu-Gyeongbuk', role: 'coach' },
  '3522': { team: 'HDHolyRams', region: 'Daegu-Gyeongbuk', role: 'player' },

  // Busan-Gyeongnam Region Teams (Region: 4)
  '4711': { team: 'GSDragons', region: 'Busan-Gyeongnam', role: 'coach' },
  '4972': { team: 'GSDragons', region: 'Busan-Gyeongnam', role: 'player' },
  '4891': { team: 'DSBlueDolphins', region: 'Busan-Gyeongnam', role: 'coach' },
  '4542': { team: 'DSBlueDolphins', region: 'Busan-Gyeongnam', role: 'player' },
  '4041': { team: 'DALeopards', region: 'Busan-Gyeongnam', role: 'coach' },
  '4482': { team: 'DALeopards', region: 'Busan-Gyeongnam', role: 'player' },
  '4121': {
    team: 'DEUTurtleFighters',
    region: 'Busan-Gyeongnam',
    role: 'coach',
  },
  '4782': {
    team: 'DEUTurtleFighters',
    region: 'Busan-Gyeongnam',
    role: 'player',
  },
  '4781': { team: 'PNUEagles', region: 'Busan-Gyeongnam', role: 'coach' },
  '4222': { team: 'PNUEagles', region: 'Busan-Gyeongnam', role: 'player' },
  '4221': { team: 'BUFSTornados', region: 'Busan-Gyeongnam', role: 'coach' },
  '4672': { team: 'BUFSTornados', region: 'Busan-Gyeongnam', role: 'player' },
  '4761': { team: 'SUDevils', region: 'Busan-Gyeongnam', role: 'coach' },
  '4992': { team: 'SUDevils', region: 'Busan-Gyeongnam', role: 'player' },
  '4621': { team: 'UOUUnicorns', region: 'Busan-Gyeongnam', role: 'coach' },
  '4822': { team: 'UOUUnicorns', region: 'Busan-Gyeongnam', role: 'player' },
  '4811': { team: 'KMOUVikings', region: 'Busan-Gyeongnam', role: 'coach' },
  '4052': { team: 'KMOUVikings', region: 'Busan-Gyeongnam', role: 'player' },

  // Amateur Teams (Region: 5)
  '5761': { team: 'GunwiPhoenix', region: 'Amateur', role: 'coach' },
  '5552': { team: 'GunwiPhoenix', region: 'Amateur', role: 'player' },
  '5111': { team: 'BusanGryphons', region: 'Amateur', role: 'coach' },
  '5982': { team: 'BusanGryphons', region: 'Amateur', role: 'player' },
  '5731': { team: 'SamsungBlueStorm', region: 'Amateur', role: 'coach' },
  '5432': { team: 'SamsungBlueStorm', region: 'Amateur', role: 'player' },
  '5781': { team: 'SeoulGoldenEagles', region: 'Amateur', role: 'coach' },
  '5872': { team: 'SeoulGoldenEagles', region: 'Amateur', role: 'player' },
  '5991': { team: 'SeoulDefenders', region: 'Amateur', role: 'coach' },
  '5522': { team: 'SeoulDefenders', region: 'Amateur', role: 'player' },
  '5171': { team: 'SeoulVikings', region: 'Amateur', role: 'coach' },
  '5662': { team: 'SeoulVikings', region: 'Amateur', role: 'player' },
  '5871': { team: 'IncheonRhinos', region: 'Amateur', role: 'coach' },
  '5422': { team: 'IncheonRhinos', region: 'Amateur', role: 'player' },

  // Admin access
  '0224': { team: 'ADMIN', region: 'ALL', role: 'admin' },
};
